version: '3.7'


networks:
  web:
    driver: bridge
  auth:
    driver: bridge
  urls:
    driver: bridge


services:
  auth:
    container_name: us_auth
    build:
      context: ./api/auth
    environment:
      PYTHONASYNCIODEBUG:      ${PYTHONASYNCIODEBUG}
      PYTHONDONTWRITEBYTECODE: ${PYTHONDONTWRITEBYTECODE}
      SECRET_KEY:              ${SECRET_KEY}
      ACCESS_TOKEN_TTL:        ${TOKEN_TTL}
      REFRESH_TOKEN_TTL:       ${REF_TOKEN_TTL}
    tty: true
    restart: always
    volumes:
      - ./api/auth:/app
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - auth
    ports:
      - 8080:8080
    depends_on:
      - us_postgres_auth
      - us_redis_auth

  us_postgres_auth:
    container_name: us_postgres_auth
    image: postgres
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    tty: true
    restart: always
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    networks:
      - auth
    ports:
      - 5432:5432

  us_redis_auth:
    container_name: us_redis_auth
    image: redis
    volumes:
      - ./.data/redis:/data
    tty: true
    restart: always
    networks:
      - auth

  nginx:
    container_name: us_nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web
      - auth
      - urls
    ports:
      - 80:80
    depends_on:
      - auth
