version: '3.7'


networks:
  web:
    driver: bridge
  auth:
    driver: bridge
  urls:
    driver: bridge


services:
  auth:
    container_name: us_auth
    build:
      context: ./api/auth
    environment:
      PYTHONASYNCIODEBUG:      ${PYTHONASYNCIODEBUG}
      PYTHONDONTWRITEBYTECODE: ${PYTHONDONTWRITEBYTECODE}
      SECRET_KEY:              ${SECRET_KEY}
      ACCESS_TOKEN_TTL:        ${TOKEN_TTL}
      REFRESH_TOKEN_TTL:       ${REF_TOKEN_TTL}
    tty: true
    restart: always
    volumes:
      - ./api/auth:/app
    networks:
      - auth
#    ports:
#      - 8080:8080
    depends_on:
      - us_postgres_auth
      - us_redis_auth

  us_postgres_auth:
    container_name: us_postgres_auth
    image: postgres
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    tty: true
    restart: always
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    networks:
      - auth
    ports:
      - 5432:5432

  us_redis_auth:
    container_name: us_redis_auth
    image: redis
    volumes:
      - ./.data/redis_auth:/data
    tty: true
    restart: always
    networks:
      - auth

  urls:
    container_name: us_urls
    build:
      context: ./api/urls
    environment:
      PYTHONASYNCIODEBUG:      ${PYTHONASYNCIODEBUG}
      PYTHONDONTWRITEBYTECODE: ${PYTHONDONTWRITEBYTECODE}
      SECRET_KEY:              ${SECRET_KEY}
      SHORT_URL_MIN_TTL:       ${SHORT_URL_MIN_TTL}
      SHORT_URL_MAX_TTL:       ${SHORT_URL_MAX_TTL}
    tty: true
    restart: always
    volumes:
      - ./api/urls:/app
    networks:
      - urls
#    ports:
#      - 8081:8080
    depends_on:
      - us_redis_urls

  us_redis_urls:
    container_name: us_redis_urls
    image: redis
    volumes:
      - ./.data/redis_urls:/data
    tty: true
    restart: always
    networks:
      - urls


  nginx:
    container_name: us_nginx
    image: nginx
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html/
    networks:
      - web
      - auth
      - urls
    ports:
      - 80:80
    depends_on:
      - auth
      - urls
