auth:
  host: localhost
  port: 80

  postgres:
    host: us_postgres_auth
    port: 5432
    database: url_shortener_test
    user: url_shortener
    password: 1qaz2wsx
    minsize: 1
    maxsize: 5

  redis:
    host: us_redis_auth
    port: 6379
    password: 1qaz2wsx
    database: 1
    minsize: 1
    maxsize: 5
