const SHORTIFY_URL         = "SHORTIFY_URL";
const SHORTIFY_URL_REQUEST = "SHORTIFY_URL_REQUEST";
const SHORTIFY_URL_FAILURE = "SHORTIFY_URL_FAILURE";
const SHORTIFY_URL_SUCCESS = "SHORTIFY_URL_SUCCESS";

const FETCH_URLS                    = "FETCH_URLS";
const FETCH_USER_OWNED_URLS_REQUEST = "FETCH_USER_OWNED_URLS_REQUEST";
const FETCH_USER_OWNED_URLS_FAILURE = "FETCH_USER_OWNED_URLS_FAILURE";
const FETCH_USER_OWNED_URLS_SUCCESS = "FETCH_USER_OWNED_URLS_SUCCESS";

const CREATE_USER         = "CREATE_USER";
const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

const LOGIN_USER         = "LOGIN_USER";
const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

const LOGOUT_USER         = "LOGOUT_USER";
const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

const REFRESH_TOKENS         = "REFRESH_TOKENS";
const REFRESH_TOKENS_REQUEST = "REFRESH_TOKENS_REQUEST";
const REFRESH_TOKENS_SUCCESS = "REFRESH_TOKENS_SUCCESS";
const REFRESH_TOKENS_FAILURE = "REFRESH_TOKENS_FAILURE";

const REFRESH_URLS_BUTTON_CLICK = "REFRESH_URLS_BUTTON_CLICK";


export {
  SHORTIFY_URL,
  SHORTIFY_URL_REQUEST,
  SHORTIFY_URL_FAILURE,
  SHORTIFY_URL_SUCCESS,

  FETCH_URLS,
  FETCH_USER_OWNED_URLS_REQUEST,
  FETCH_USER_OWNED_URLS_FAILURE,
  FETCH_USER_OWNED_URLS_SUCCESS,

  CREATE_USER,
  CREATE_USER_REQUEST,
  CREATE_USER_FAILURE,
  CREATE_USER_SUCCESS,

  LOGIN_USER,
  LOGIN_USER_REQUEST,
  LOGIN_USER_FAILURE,
  LOGIN_USER_SUCCESS,

  LOGOUT_USER,
  LOGOUT_USER_REQUEST,
  LOGOUT_USER_FAILURE,
  LOGOUT_USER_SUCCESS,

  REFRESH_TOKENS,
  REFRESH_TOKENS_REQUEST,
  REFRESH_TOKENS_FAILURE,
  REFRESH_TOKENS_SUCCESS,

  REFRESH_URLS_BUTTON_CLICK
};
